env:
  browser: true
  jest: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
settings:
  import/resolver:
    alias:
      map:
        - [common, ./src/common]
        - [components, ./src/components]
        - [i18n, ./src/i18n]
        - [themes, ./src/themes]
        - [utils, ./src/utils]
      extensions:
        - .ts
        - .js
        - .jsx
        - .json
extends: airbnb
rules:
  arrow-parens:
    - error
    - always
  indent:
    - off
  max-len:
    - error
    - code: 200
  object-curly-newline:
    - error
    - ObjectExpression:
        multiline: true
        consistent: true
      ObjectPattern:
        multiline: true
        consistent: true
      ImportDeclaration:
        multiline: true
        consistent: true
      ExportDeclaration:
        multiline: true
        consistent: true
  react/jsx-filename-extension:
    - warn
    - extensions:
        - .js
        - .jsx
  react/jsx-no-bind:
    - error
    - allowArrowFunctions: true
  react/prefer-stateless-function:
    - off
  react/prop-types:
    - off
  react/jsx-props-no-spreading:
    - off
  semi:
    - error
    - never
  template-curly-spacing:
    - off
