env:
  browser: true
  jest: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
settings:
  import/resolver:
    alias:
      map:
        - [common, ./src/common]
        - [components, ./src/components]
        - [i18n, ./src/i18n]
        - [themes, ./src/themes]
        - [utils, ./src/utils]
      extensions:
        - .ts
        - .js
        - .jsx
        - .json
extends: airbnb
rules:
  react/jsx-filename-extension:
    - warning
    - extensions:
        - .js
        - .jsx
  react/jsx-no-bind:
    - error
    - allowArrowFunctions: true
  react/prefer-stateless-function:
    - off
  react/prop-types:
    - off
